/**
 * @file trill_error.h
 * @brief Trillbit SDK error codes
 * 
 * @author Ravikiran Bukkasagara
 * @date 23-Feb-2022
 *
 */

#ifndef INCLUDE_TRILL_ERROR_H_
#define INCLUDE_TRILL_ERROR_H_

#define TRILL_ERR_BASE -2000

enum {
	TRILL_ERR_INVALID_PARAMETERS=TRILL_ERR_BASE,
	TRILL_ERR_INVALID_LICENSE_DATA,
	TRILL_ERR_OUT_OF_MEMORY,
	TRILL_ERR_LICENSE_NOT_FOR_THIS_DEVICE,
	TRILL_ERR_FAILED_TO_GET_DEVICE_ID,
	TRILL_ERR_INVALID_CK,
	TRILL_ERR_INVALID_CK_NONCE,
	TRILL_ERR_PARAM_EXCEEDS_ALLOWED_VALUE,
	TRILL_ERR_PARAM_VALUE_TOO_SMALL,
	TRILL_ERR_OS_SEM_CREATE_FAILED,
	TRILL_ERR_RX_OR_TX_NEEDED,
	TRILL_ERR_NO_RX_CHANNELS_ENABLED,
	TRILL_ERR_UNKNOWN_FTS_STATE,
	TRILL_ERR_FTS_NOT_FOUND,
	TRILL_ERR_FTS_DONE,
	TRILL_ERR_UNKNOWN_TRILL_STATE,
	TRILL_ERR_AUDIO_BLOCK_ADD_FAILED,
	TRILL_ERR_AUDIO_GET_BLOCK_FAILED,
	TRILL_ERR_AUDIO_SEM_REL_TO_WR_FAILED,
	TRILL_ERR_AUDIO_SEM_REL_TO_RD_FAILED,
	TRILL_ERR_AUDIO_INVALID_OFFSET,
	TRILL_ERR_AUDIO_REQ_BLOCKS_EXCEEDED,
	TRILL_ERR_AUDIO_SEM_ACQ_RD_FAILED,
	TRILL_ERR_AUDIO_TX_BLOCK_NOT_AVAILABLE,
	TRILL_ERR_AUDIO_SEM_ACQ_WR_FAILED,
	TRILL_ERR_DATA_DEC_FFT_TB_EXCEEDS_FFT_SIZE,
	TRILL_ERR_DATA_DEC_FFT_INVALID_FFT_SIZE,
	TRILL_ERR_DATA_DEC_CFG_INVALID_FRAME,
	TRILL_ERR_DATA_DEC_CFG_UNKNOWN_CFG,
	TRILL_ERR_DATA_DEC_CFG_FREQ_COMB_EXCEEDS_MAX_VALUE,
	TRILL_ERR_DATA_DEC_GET_CFG_FAILED,
	TRILL_ERR_DATA_DEC_SYMBOLS_EXCEEDED,
	TRILL_ERR_DATA_DEC_SYMBOLS_OVER,
	TRILL_ERR_FFT_INIT_FAILED,
	TRILL_ERR_DATA_DEC_CRC_CHECK_FAILED,
	TRILL_ERR_CONV_DELAY_EXCEEDS_ALLOWED_VALUE,
	TRILL_ERR_PL_CONFIG_UNKNOWN_CONFIG,
	TRILL_ERR_PL_CONFIG_UNKNOWN_SYMBOL_DECODE_METHOD,
	TRILL_ERR_PL_CONFIG_NO_SYMBOLS,
	TRILL_ERR_DATALINK_BROADCAST_REQ_NOT_IMPLEMENTED,
	TRILL_ERR_DATALINK_INVALID_HEADER_LENGTH,
	TRILL_ERR_DATALINK_UNKNOWN_SSI,
	TRILL_ERR_DATALINK_SSI_NOT_IMPLEMENTED,
	TRILL_ERR_DATALINK_ENCRYPTION_FAILED,
	TRILL_ERR_DATALINK_TX_SEM_REL_TO_SEND_FAILED,
	TRILL_ERR_DATALINK_TX_SEM_REL_TO_READY_FAILED,
	TRILL_ERR_DATALINK_TX_SEM_ACQ_TO_SEND_FAILED,
	TRILL_ERR_DATALINK_PAYLOAD_TOO_LONG,
	TRILL_ERR_USER_ABORTED_TX
};

#endif /* INCLUDE_TRILL_ERROR_H_ */
